---
title: Capable Hands
date: 2350-10-13T18:18:28-07:00
draft: false
---
* Exploring
** Rock Facts
- The rock is weird - hard to determine dimensions, it seems like a circle.
- The rock is weirdly light - trying to hang from it just pulls it a little bit downward.
- The spring starts bubbling, there's something in there
- We try to pull Digby to safety
** Geyser
- Bubbling geyser!
- Pufferfish, with tiny fins/wings
- Weird turqoise crawling slimes.
- Sam said we heard some similar sounds from other nearby geysers?
- We're trying to get to higher ground
- From a vantage point: Four other geysers (some super high, ~120 ft) shooting up, with puffer fish as well.
- There is mild radiation from the geyser - some source of heat beneath it - possibly a radioactive heat source? The water itself is nontoxic.
- The pufferfish seem to be communicating - call and response?
- The slimes are acidic, they start dissolving the rock on contact
- The geysers die down, the pufferfish take a breath, and begin floating on the wind (like balloons)
- Question: Are the slimes dissolving the grass? No.
- The slimes do have a heat signature.
- New plan: Get uphill, try to get a camping spot and a radio signal.
- As we climb, the grass shifts to rock.
- The grass is strong, and quite corrosive-resistant.
- So we have potential energy sources: Purple substance, radioactive heat source/geothermals.
* Mysterious
** Break on Through...
- We're trying to assess the planet for a magnetic field. There is one. Magnetic "North" seems to be roughly the mountain northeast? Or that mountain just has a lot of metal. Probably the former.
- The compass points to the cliffside - a specific spot in the wall?
- It's a patch of metal in the cliffside!
- And a strange purple sparkle around it. Ions or something?
- It's an image!!
- There is sentient life on this planet! Capable of some kind of writing?
- The writing: Six symbols, ABACDB
- Martin said "where am I" and then slumped
- "It feels like your eyes have just seen a very bright light"
- "We don't have the key right now"
- The asterisks don't line up with the symbols
- It looks exactly like the Lodestar logo.
- There were stars.
- TODO: Check if the central lodestar, or a six star constellation, shows up in the night sky.
- TODO: Check the ship databanks - source of lodestar logo?
- Specifically, the logo is a 4-pointed star on a trapezoid, weirdly similar to lodestar.
- Martin doesn't seem amused by blaming the door on ghosts.
** Erebor
- Shipmind: We find a few files from ~30 years ago - possibly related to this planet, or to the door?
- "Project Erebor": Admin access needed.
- TODO: Check if we can get the captain or first mate to access it. Or a colony administrator?
** Martin's Dream
- Chatting with Martin about the door.
- "You know when you have a dream that feels so real? Like you could reach out and touch it"
- "A weird robot said something about a duke?"
- Connection to Erebor: "The robot mentioned something about Erebor?"
- "Speak 'friend'."
- "Must be there linguistically, but /here/ (gesture: in my head) physically"
- "Something about a Duke"
- "A weird place with red and purple flowers"
- "She's underground, how should it trust her?"
- "1 mile underground, NE, there's weapons and food"
- "You can only get there if you manage to say friend"
- So abstractly we need to understand the language a little better before doing anything with it.
** Erebor Lore: Courtesy of our Counsel
- Scientists were sent on a trip for project Erebor - prominent scientists (specifically 3 of them).
- Ship crashed (?) or lost contact, but basically went AWOL
- Lodestar couldn't find them
- Names:
  + Duke Landon
  + Kiki Fey
  + Fordham Ishmael
- Duke? Like in the dream?
- The logo might be the lodestar logo from 30 years ago.
- Martin saw a symbol, was told to "keep an eye out"
- Martin drawing the symbol makes him instantly pass out.
- After a few minutes, the purple moss in his inventory disintegrates, as does the symbol.
- Something magical is here. This is worrying.
- Martin took stress from the various shenanigans
* Over the Hills
- Purple rocks past the peak
- We're above a purple ion cloud
- Part of the engine crashed near the ocean, with our people.
- Engine got swept in to the stormcloud
- The cloud isn't getting closer, it's floating over the water.
- A piece of the ship has crashed to our Northwest (about 1.4 miles NW) - barracks.
** Predators Near the Ship
- The creatures don't like sound. Martin's whistle?
- They're fast and sneaky, don't split the party
- Visible from a distance, but up close hard to see - invisibility?
- Plan: Jury-rig some speakers, use the noisemaker, and get guns from the barracks.
- Stargazing: Tentacles hovering close to the throat of Consolus. A weird 10-foot long, human-thickness worm-creature with tentacles that attacks. Somewhat cold-resistant, high AC head and tentacles.
* Bestiary
** Predators Near the Ship
- The creatures don't like sound. Martin's whistle?
- They're fast and sneaky, don't split the party
- Visible from a distance, but up close hard to see - invisibility? Perhaps an afterimage
- Plan: Jury-rig some speakers, use the noisemaker, and get guns from the barracks.
- Stargazing: Tentacles hovering close to the throat of Consolus. A weird 10-foot long, human-thickness worm-creature with tentacles that attacks. Somewhat cold-resistant, high AC head and tentacles.
** Aquamarine Slimes
- Highly acidic
- Don't corrode the grass though
- Slow, seemingly non-hostile
- They have a heat signature at least, but otherwise hard to track (camouflage with the grass)
** Puffers
- Pufferfish, with tiny fins/wings
- The pufferfish seem to be communicating - call and response?
- The geysers die down, the pufferfish take a breath, and begin floating on the wind (like balloons)
** Dr. Worm
- Tried to eat our doctor.
- About the thickness of a human, 10ft long, 4 tentacles, and a mouth that bites
- Somewhat cold-resistant, high AC on the head and tentacles.
- Quite stealthy
- Found in caves, as far as we can tell
* Scavenging
- So we have potential energy sources: Purple substance, radioactive heat source/geothermals
- Some kind of purple moss exists
- The turqoise grass is corrosion resistant (corollary: indigestible)
