---
title: Of Course You Have Purple Eyes and Pronouns
date: 2530-12-04T21:15:17-05:00
draft: false
---
* NPC tracking
** Digby 
HP: 11/11      STRESS: 2
AC: 12         Armor: 4
Affliction - Broken Leg is negated by Power Armor
Affliction - Broken Arm
** Juniper
HP: 10/10      STRESS: 0
AC: 9              Armor: 1
** Ashleigh
HP: 10/10      STRESS: 0
AC: 9              Armor: 1   
** Abi
HP: 10/10      STRESS: 5
AC: 9              Armor: 1   

* Dropoff
- Corrin was heading to a spot in the jungle, based on coords they received over the radio.
- Coordinates - match up with the hatch we spotted in the jungle.
* Yavin IV
** Ghosts
- There are no Could-Have-Beens in the wood. This tracks with what Rick said.
- Still, it's interesting - why did they vanish? What's changed?
- Still see them, just not much around the ship
- The ghosts on the ship have been dissipating, "breaking", ever since the other ghosts started
- Blue ghosts are still around the mountain, but the ship is free.
- Rick hypothesis: The ghosts died in the other timelines.
** Halifax
- "Whatever position and accolades Dr. Landon held as a Lodestar scientist, he's been alone on a strange planet (that is known to have strange effects on people's minds/sanity) for 30 years. So even if he seems reliable, he's very much a wild card and we should be appropriately cautious in our dealings with him."
- He's still going to talk to Dr. Landon, but we've convinced him to be cautious, and to consult Evelyn before committing to 
- Some dispute - Halifax doesn't seem to want to leave this place.
- One of the sub-administrators (the one in charge of law/justice stuff) seems to be pretty opposed to this.
** Fordham
- Found the wiki article on the databanks 
- General engineer on Project Erebor
- Older fellow, worked on a lot of mechanical-engineering stuff, including J-drives - relatively minor player in a lot 
- Specialty: J-drives, and such like. So Fordham did the Jdrive hardware, Landon did the astrogation software.
- His psychological weakness: He's been laughed at for being spiritual a lot. "Exadin" is the religion.
- Favorite color: Yellow
- Food: Stale pop tarts (maybe a joke)
  
* Stormborn Isle
- A cluster of black clouds and angry red lightning - both magic
- Black - same as the ghosts - modalities?
- Observation: With panspectrals+magesight
- Engine would be near the center of the isle.
- The island is quite large
- There's a pattern to the storm - the lightning seems to hit the red vines/weeds, and speed their growth - like a timelapse
- Lightning strikes the same place twice
- There's no sign of the boat that Nora saw, 
- She uses the last bit of focus, to better fly in without wrecking the ship.
- Blackish trees with peeling runes(?) on the bark.
- Strangely floaty plants - vines and weeds (red)
- Esper takes a shot of Psych. So she's psyched up.
- The engine's signal is hoping all over the place. 
- Hypothesis - modalities - different /possible/ locations of the engine.
- A structure that looks like an inverted pyramid
- We flew right into the Eye of the Storm.
- Esper got a fucking 21.
- There's red rapidly-growing grass creeping onto the landing gear.
- Focus is no longer active, psych still is
- You hear a twang from the inverted pyramid’s top
- Like the pluck of a string. Then again. In a rhythm. 
- There are triangular cuts in the base (well, the point - the bit on the ground) of the pyramid.
- Strange little figures - headless creatures, with antennae facing backwards 
- They're running off towards the storm

** Top of the pyramid
- Covered with black trees, and vines
- The sound is coming from behind one of the trees
- There's a figure playing an instrument
- A figure: Quite tall (8-9ft), currently sitting
- It's the three-eyed fellow!
- They're quietly playing 
- The eyes are mechanical - lights.
- Hypothesis - he's Ishmael's equivalent of the Emissary
- We see the engine in the distance, but it seems to move (~100ft) every time lightning flashes
- When asked about if he knows Morse code - he part nods, and then shakes his head
- Diversity win! This three-eyed semi-robotic creatures uses he/they pronouns!
- He wants us to call him "Ishmael"
- The bunker is apparently theirs.
- He parachutes down to the ground using a pufferfish parachute
- He came with the expedition - so perhaps a human or an expendable.
- Suddenly the lightning stops, and we begin to see blinding blasts of light
- Some sort of room/dome.
- Ishmael is coursing with a variety of magical signatures - including the staff, which seems to resemble Landon's or Ellie's
- Larger versions of the antenna-creatures are patrolling the bunker
- Bunker - labelled "Stormborn" (a GoT reference, not LOTR), and the same symbol for mankind
- The creatures freak out and attack Consolus
- Our Wanderer draws symbols - red and green - and snaps the bones of two of the creatures
- Esper falls to a -3. So stress 4, take an affliction after the scene 

** Bunker
- We made our way into the bunker at great personal cost
- The Wanderer pointed us to the computer terminal

*** Files available
- Symbols
- Color Theory
- Stormborn Isle Outpost
- Gates Active
- Complete Sentence
- Biocomputational Enhancements
- EREBOR and magic
- URGENT: COMMS LOST
- The Septids
- Corporate Bullshit
- ASMO Down

*** Files we accessed
**** URGENT: COMMS LOST
Subject: URGENT - COMMS LOST
Has anyone been able to make contact with Sol recently? Kuiper? Any colony for that matter? 


Re: URGENT - COMMS LOST
Duke says it’s some kind of Astrogation anomaly. Like the planet itself has moved? How the hell are we supposed to get home?

Re: URGENT - COMMS LOST
Patience. The planet will provide a way; we simply must find it.  Lothlorien will continue its studies of these ‘runes’ and I suggest other places do the same. We can sustain ourself until contact is established, and by then have something to present.

**** Stormborn
- From Duke
- Outpost that could handle the stormy weather 
- "Link to the blue is established, but radio contact is limited"
- "Jump gate should be established within a week"
- "Dilation effects" - more time spent on the isle than passes outside
- Hypothesis - blue refers to the blue moon, where the moon outpost is
  
***** Full text
Duke here,

Man has conquered the storm! Or, more precisely, the Stormborn Isle. We’ve built a new outpost over here that should be able to withstand the extreme (and extremely fickle) weather conditions. Radio contact is limited, but a link to the Blue is established, and a Jump Gate should be online within the week!

Happy exploring and go science!!!

(PS: Be careful about the time dialation!)

  
**** ASMO Down
Subject: ASMO is down

The Automated System for Multipurpose Operations has been taken down for maintenance yesterday, due to apparent malfunctions in the AI Core. Doctors Ishmael and Duke are working on it immediately; details are sparse but given the involvement of the Doctors, it’s likely serious. Stand by for further updates, and try using the primitive AILS algorithm for relevant searches.

**** Moria
- A shadowy grey-haired face, from Martin's vision
- "Subject C37", as slime bangs from within a crate in the background.
- "I don't know what Kiki's done with it but it seems bent on destruction... showing some sign of intelligence"
- "Mimicry is well-established, it responds well to electricity."
- "All over the planet, they seem keen on consuming what they encounter. We found this creature impersonating by one of our scientists".
- "Ishmael out"
- Koa - their team got attacked by an Ishmael-slime.
- Ok we need to be careful about slimes. Use magesight, just to be sure
- Hypothesis - is Dr. Landon a slime

**** Last File - Ishmael's Pick
- "It is done. The first phase."
- "I will not let this evil fester, I know they plan to steal it."
- "At the heart of the mountain. The beating, thumping, heart"
- Nila and Soup get a sense/vision/connection to a cauldron, swirling at this last phrase.
- "It cannot be contained, it cannot be controlled. They seek to steal it. Duke is a charlatan. He will try anything to get it elsewhere"
- "Kiki - what she wants, I fear even more. Suppression, control of the galaxy."
- "I've ended these abominations. I will end this heart too... It is the only way to keep the infection of this planet (at bay?)."
- "Fordham Ishmael, pleading for all of you to join me. We cannot let them destroy the world."
*** Conversation
- The Wanderer is revealed to be Ishmael - presumably after several phases, and taking on horrifically high IT.
- He confirms there is no way to restore his speech/writing.
- Hypothesis: High IT + infection + (however many phases of plan he's at) causes the world to take over your brain; and destroys your ability to write any language other than this one.
- This gives context to his inability to understand Morse Code.
- We gave the Wanderer a radio.
