---
title: "The Council Will Decide Your Fate"
date: 2531-01-07T21:39:05-05:00
draft: false
---
* Stress
All zeroed out by a long journey! We're so back!
* Rescue
- Lt Dubois of the Sol Authority. I know what you are, Jacob.
- A dedicated rescue ship. Space coast guard?
- We're trying to convince them to keep Dr Landon in cryo. Our excuse - quarantine; he may be infected.
- They are suspicious, but not hostile
** Castor
- Sol Authority system; their primary "frontier base".
- Six stars; 3 binary systems.
- One planet (New Provont); habitable but not /nice/.
- Sizable spaceport
- Sol Authority outpost.
** Our Story
- Meant to be on a mission to Serenity
- Landed in a different system; Incognita
- Deeply strange planet.
- Discovered a previous Lodestar expedition (Erebor) had crash-landed here ~20 years ago, met up with them.
- Discovered intelligent life on the planet (Septids), and that the previous expedition had treated them horribly (experimentation, etc.)
- Got attacked by one of the factions of the previous expedition; left in a hurry to escape and get help
** Station
- We got confined to quarters
- Spent 2 days approaching the spaceport; Sol Authority outpost basically.
- They have a Vanguard - a small jump-capable warship
** The Council Decides Our Fate
- Director Chelnikova, Strategic Intelligence. ~60? year old woman with piercing glare. She has a strong Russian accent.
- Dr Redfern; Lady who keeps checking her watch (and realising it's hidden under her suit)
- Commander Sato; Short woman who Consolus recognises; an Ensign when he served, now higher rank.
- They seem to be familiar with the planet's magic. Although that may just be from us.
* Consensus
- We told them everything as best as we know it. The Duke is on the planet; held in quarantine but not imprisoned, while they investigate and the bureaucracy bureaucracies.
- We are confined to Commander Sato's ship. Nominally just as guests.
- Consolus can hopefully parlay us into an advisory role, and/or convince her to let Esper plug in to the system so we can rematch ASMO.
- Digby and Consolus weaned Esper off psych and onto painkillers
- We try to develop a rapport with Commander Sato, and with the pilots. 
- In particular we're trying to help them simulate skywhales and other threats.
