---
title: Goodnight, Moon(s)
date: 2531-01-13T21:46:27-05:00
draft: false
---
* Miscellaneous
- Martin gets appointed captain for the journey
- A lot of the crew stays behind; including Consolus (for continuing search and rescue)
- Bellringer is a Sol Authority spy, good for her
- Ellie is doing great, and tattooed the sigils for "heal" and "move" over her wrist scars. I have known them for like 5 minutes but even so we love to see it
- Redjoy is just Palpatine; they want spaceships and UNLIMITED POWER
- Administrator Martinez has a secret wife (finally, that's explained)
- Some slimes and handlings requested and were granted Sol Authority citizenship, and passage off-world
- We established a settlement on the moon, and also a small human research station on the planet
- Planet coords are classified, so human access to it is limited
- Linnea and Raspberry were both creatures of this planet (Raspberry was a slime piloting the corpse of a colonist, Linnea was also a slime)
- Raspberry fused with Bradamont. Sure. Why not.
- Joe Brew has a cult of pikminoids who will Jonestown themselves to power his levitation/antigrav
- Halifax is a frog now. Like, permanently
- The Duke trial is still happening, his supercomputer is now part of the investigation/evidence
- Rick's ghost/impression is transferred to a shuttle, and asked to help in the rescue attempts; he's bound to this planet but he'll remain sentient and he'll get to keep piloting
* Negotiations
** Characters for the Negotiation

**Bluehope**, a Handling from the jungle who lead the political opposition to Fey in her camp in the jungle.

**Redjoy**, a Handling from the jungle who wants a way to survive the cyclical cataclysms onworld. Former general for Fey.

**Greenpeace**, a handling from the  Fog/Beach intent on leaving the Heart, its cycle, and the planet undisturbed.

**“Fusion” Nisha**, formerly Nisha Acarya of the Midas touch, now fused with a strange teal mold on her face. A former general for Fey.

**Flywheel**, the spokesperson for the young but industrious species of intelligent slime

**Director Pchelnikova**, leader of the Sol Authority presence here.

**Doctor Redfearn**, Sol Authority scientist tasks with studying magic.

**Administrator Martinez**, acting administrator of Lodestar’s Serenity Valley expedition.
* Treaty Summary
A treaty on Incognita was reached to grant the wonders of magic to humanity without treading on the autonomy of the world’s intelligent life. Among its official pages, it contained the following points:

- The heart was left onworld, and the Cauldron totally off limits to humanity. This was enforced by its new mechanical guardian, a former Expendable ascended to something higher…
- Humanity’s presence onworld was for research only, stemming from a small base in the desert. Their bigger presence was on the Hidden Moon, where it was agreed they could operate a center to study magic. In exchange for their knowledge, handlings and slimes were provided lessons and training with human technology, including spacefaring capabilities.
- The system was kept secret from most of humanity, with only top Sol Authority officials knowing its location. Travel was restricted, and corporations were prohibited entirely.
- The Fog, Beach and Cauldron were off limits to humanity due to Handling wishes. In accordance with the Star Septids, a small sept of 7 Handlings, the Heartland Crater on the North Pole of the Hidden Moon was also off limits.
- Many living things onworld, particularly the slimes, sought a journey in the stars. They were granted passage offworld to live life anew as recognized Sol citizens.
