---
title: Get thee to the Space-Hague
date: 2531-01-03T14:18:10-05:00
draft: false
---
* Duke Planning
- Plan: Drug him to knock him out for a week, and turn him in to the solar authority, i.e the space hague. Case: Abusing intelligent life.
* The amazing Mauri(c)e and her astrogation capabilities
- She's taken off in a flying cryopod; the skies near her are dense with enemies.
- 8 manteeth, 2 skywhales. The whales are on space-redbull
- There's humming on the radio, from Maurie's end
- We have Maurie and Benedict
- ASMO: A weird eldritch centipede, the remains of Duke's ship. Apparently has beef with him and Ishmael. It's hunting us
- We manage to jump, barely.
- Esper gets addicted to psych; both physical and psychological dependence
- Our ship is now dead floating in space (1hp hull); we need to spend a few days repairing it before we can get to the colony.
- We specifically jumped to a non-Lodestar colony.

* Plan
- Ben and Maurie: Stay down, out of the fight as far as possible
- Digby: Deny them the machine gun
- Consolus tries to surprise-sever a gun arm on Landroid Alice; trying to keep it not-dead but neutralised
- The rest of us gang up on Landroid Bob, rip it to shreds
- Then we deal with the Duke; either shove him into cryo or just take him prisoner or something.
- When shooting heat/lasers, the arm is weak to cold. When shooting ice, weak to heat.
* Execution
- We killed one Landroid and disabled the other.
- Duke wipes most of the nav data from his Landroids.
- So we need him to get back, basically. We've promised him that we will do him no harm and also that we'll take him to the space hague.
- He's sharing the data with Maurie, so we can safely send him to the Hague. Probably.

* Drifting through space: Proposed Plan
- Martin, Evelyn, Benedict all go in cryo.
- Esper goes in cryo for the 3 days of fixing.
- Duke goes in cryo as soon as they are able (i.e done with the calculations stuff).
- If we are ever at a point where Maurie can enter cryo (i.e the route is locked in) she goes in as well.
- Digby and Consolus stay out the whole time.

So we have 3 days of 4 people awake, and 7 days of 3-4 people awake (assuming the calculations take the same time as fixing the ship). The 3-4 depends on whether we can freeze Maurie.
So a total of 12 + (21-28), i.e in between 33 and 40 person-days.
