---
title: Transmission Revealing All
date: 2530-11-26T21:06:57-04:00
draft: false
---

* 2350-10-08, Seventh Day Of The Crash, Sundown. Thorn transmitting
It seems this planet is not as unknown as we thought it was.
We've discovered a former Lodestar expedition to this planet named Project Erebor - consisting of twenty-five scientists and engineers including Duke Landon, Kiki Fey, and Fordham Ishmael.
We've had several brushes with Dr. Landon, and recently met with him in the Ion Hills.
He claims he wants to get back to Sol and bring what he's discovered back to Lodestar, and so helping us fix our ship aligns with his (stated) goals.
He seemed sympathetic to our plight, and offered us valuable help (most recently with locating the lost starboard engine). However we couldn’t manage to trust him, because he just seemed too good to be true. 

Landon identified several bunkers associated with the expedition: “Erebor” in the Ion Hills, “Stormborn” on the island beneath the storm, “Moria” at the Radlands/Rockwell, “Osgiliath” at the Beach/Fog, “Doom” at the northeastern mountain, and “Lothlorien” in the jungle.

Landon confirmed that Drs. Kiki Le Fey and Fordham Ishmael are still alive, albeit now insane or dangerous. He warned us that they are volatile and cannot be trusted, and are extremely dangerous (having access advanced technology as well as knowledge of the planet's eccentricities and ability to exploit them);
He believes Le Fey is based in the Lothlorien bunker, and Ishmael was last sighted in Rockwell.

Dr. Consolus (of our party) has compiled a fuller account of our interactions with Dr. Landon, including his explanation of the planet's eccentricities, which may be of interest (especially to any scientists or amateur naturalists among you)

** Appendix: Our Brushes with the Duke
Soon after the crash, our company climbed a promontory hill in order to get above the local radio interference, and identified a door leading to an underground structure. Martin Lockhead touched the door, and experienced visions, which included the name “Erebor”. Evelyn Escobar searched for records related to “Erebor”, and found the history of Project Erebor, and the manifest described above. At the Midas Touch, we were approached by several robots, who offered to repair the ship on behalf of “The Duke”. We declined, because we were suspicious of the unsolicited aid. The following night, Martin had further visions, including visions of a gray-haired man setting fires and killing people. This figure was later identified by Dr. Landon as Fordham Ishmael.

In the jungle, we contacted “The Duke”, who assisted us in launching the shuttle and escaping the rogue Krahl gang. “The Duke” insisted that we visit him soon, at the promontory hill. On this eighth day of the crash, we returned to the promontory hill and met Dr. Duke Landon, who styles himself “The Duke”.
** Appendix: Abbreviated Lecture Notes from Dr. Landon's Talk
Dr. Landon explained how he arrived on this planet, how his expedition collapsed, and what he has discovered about the nature of this world, and he expressed his desire to return to Sol with us.
According to Dr. Landon, the colors correspond to physical quantities: green to matter, red to energy, and blue to information. These quantities are well known to be interchangeable; this planet appears to moderate the conditions under which they are interchangeable. There is a fourth color outside the visible spectrum that corresponds to modalities or possibility, which is responsible for the crossovers into alternate timelines. These colors and the symbols form a language, which is responsible for this planet’s eccentricities. In the planet's "language", green corresponds to nouns, red to verbs, and blue to abstract concepts.
He also described a concept he calls "Interfacing Talents" (IT); an individual's ability to connect with the planet. High IT turns someone into a "zombie" (his words), a vessel for the planet's forces devoid of their own will.
Landon told us this planet’s star system moves, as if through subspace. Dr. Landon’s expedition identified this movement as an astrogation anomaly, approached to investigate, and became stranded.
